### ISSUE TITLE
Update ExtraCells 2 to a more up to date fork.

### ISSUE THREAD

**Issue by ElektroKill** [EnigmaticaModpacks/Enigmatica2Expert#1997]
### URL

https://www.curseforge.com/minecraft/mc-mods/extra-cells-2-samlam140330s-fork

### Why would you like the mod added?

The old ExtraCells 2 mod has been unmaintained for quite a while now. This new version fixes a couple of bugs with the mekanism gas integration and would be nice to have included in the pack.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion. Do you know which bugs it fixes specifically?

**Comment by ElektroKill** [comment]
Here is a list of bugs it fixes I could find using the github commit log:
- GUI title text for Gas Level Emitter
- Fixes all gases rendering as a white fluid in ExtraCells GUIs
- Selection of gas for Gas Level Emitter works properly
- Fixes ME Gas Terminal sometimes showing incorrect amounts of gas.
- Fixes Walrus UV mapping

**Comment by NillerMedDild** [comment]
Thanks for digging that up 😄 
Switching the two mods should not remove any items from existing worlds, correct?

**Comment by ElektroKill** [comment]
The `modid` is the same for both mods and the author of the fork did not change any item/block id's so it should be a drop-in replacement. The only real differences are the version number and the bug fixes.

**Comment by Beachman4** [comment]
Perhaps a shameless plug, but I maintain a fork of extra cells 2. I've made some changes to it, other than just bug fixes.

https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork
https://github.com/the9grounds/AE-Additions

Few things beyond just bug fixes:

- Added a Gas Interface - Works just like the fluid interface from AE2, but for mekanism gas
- Reworked the fluid autofiller - It now takes a fluid in it's slot and allows you to add speed. It will then autocraft buckets filled with the fluid you selected
- Reworked fluid assembler. Before it would take 9 recipes and it was horrendously slow. Now it takes capacity cards and acceleration cards.
- Allowed partitioning of fluid cells from the mod.
- Extended the config - Including allowing reconfiguring how big each cell is from the mod and how many types it can accept. 

The best thing is just the gas system works pretty flawlessly now. I've been using my mod in my personal E2E for quite some time and the gas interface is super helpful.

Now, the only downfall is that since I renamed the mod to AE Additions, there's a mapping issue. I can solve that with pretty easily with an event called `MissingMappings`, however, since I also removed the deprecated fluid parts, that changed around the meta number for each part(i/o buses, terminal).

I can look into trying to fix this.

If I can figure that out, I'd be happy to throw up a PR to implement my mod into the modpack.

**Comment by ReiDaTecnologia** [comment]
Acceleration Cards on Fluid Assemblers? hell yeah! that is enough for me to give you a thumbs up :D

> Perhaps a shameless plug, but I maintain a fork of extra cells 2. I've made some changes to it, other than just bug fixes.
> 
> https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork https://github.com/the9grounds/AE-Additions
> 
> Few things beyond just bug fixes:
> 
> * Added a Gas Interface - Works just like the fluid interface from AE2, but for mekanism gas
> * Reworked the fluid autofiller - It now takes a fluid in it's slot and allows you to add speed. It will then autocraft buckets filled with the fluid you selected
> * Reworked fluid assembler. Before it would take 9 recipes and it was horrendously slow. Now it takes capacity cards and acceleration cards.
> * Allowed partitioning of fluid cells from the mod.
> * Extended the config - Including allowing reconfiguring how big each cell is from the mod and how many types it can accept.
> 
> The best thing is just the gas system works pretty flawlessly now. I've been using my mod in my personal E2E for quite some time and the gas interface is super helpful.
> 
> Now, the only downfall is that since I renamed the mod to AE Additions, there's a mapping issue. I can solve that with pretty easily with an event called `MissingMappings`, however, since I also removed the deprecated fluid parts, that changed around the meta number for each part(i/o buses, terminal).
> 
> I can look into trying to fix this. The one thing I can't really fix, is if a player is still using the deprecated fluid items from Extra Cells 2 instead of the ones from AE2. I removed those items from my mod.
> 
> If I can figure that out, I'd be happy to throw up a PR to implement my mod into the modpack.
> 
> > **[Attention Required! | Cloudflare](https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c2b692d5678f3f20f88cc6d02e6ac56a0fde3c2014f2e8190e0658208993a84d/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f663734383161376463373434333534386138633038633265326231613336393637363039363230383838666462393036343165646462646166333830616532322f7468653967726f756e64732f41452d4164646974696f6e73"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[GitHub - the9grounds/AE-Additions](https://github.com/the9grounds/AE-Additions)**Contribute to the9grounds/AE-Additions development by creating an account on GitHub.

**Comment by Beachman4** [comment]
If you're curious, this is how the fluid assembler now works:

![image](https://user-images.githubusercontent.com/12937630/169673063-2e6e8dfc-011c-411d-837a-14dbdbcb4aa7.png)

By default, there is only 1 slot enabled and that would allow you to put 5 acceleration cards in. However, what I've been doing in my playthrough is 1 capacity card and 4 acceleration cards and I think that's a nice tradeoff.

**Comment by NielsPilgaard** [comment]
@Beachman4 If you can somehow make your mod compatible with existing worlds, and even do the switch in a PR, I can't refuse 😄

**Comment by Beachman4** [comment]
@NielsPilgaard I think I can find a way to do this. I'll let you know when that happens.

P.S. I also updated my mod to 1.18, bringing upgraded cells and crafting storage units along with some other additions that will be coming soon :)
