### ISSUE TITLE
Creative tank craft NBT mismatch

### ISSUE THREAD

**Issue by ylyxa** [EnigmaticaModpacks/Enigmatica2Expert#2043]
### Modpack Version

1.83

### Describe your issue.

The creative tank recipe call for portable tanks with NBT `{FluidName:"<fluidname>",Amount:32000}}`

A freshly crafted tank (or even one that's cheated in) has additional NBT `{RSControl:0b,Level:0b}`, making it unusable for a craft.

### Have you modified the modpack?

Yes

### User Modifications

Additional mods - mixinbooter 5.0, loliasm 5.6

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ylyxa#8644

**Comment by NielsPilgaard** [comment]
Did you try crafting the item? The NBT matching is weak, so it allows additional tags.

**Comment by ylyxa** [comment]
> Did you try crafting the item? The NBT matching is weak, so it allows additional tags.

Yes I have, it's not crafting.

Also the tanks are showing up red if I try to '+' the items into the table.

**Comment by ylyxa** [comment]
![image](https://user-images.githubusercontent.com/33629428/186010591-194c0bfb-dc37-431c-afcb-9938dae6ca32.png)
![image](https://user-images.githubusercontent.com/33629428/186010620-d5727ad7-2238-44cc-8116-8f8007577256.png)
Gonna attach the screenshots to here in case I derped.

**Comment by Discomanco** [comment]
Usually, the issue is not actually the tanks, even if JEI likes to complain about them. Most of the time, JEI messes up the placement of the buckets, and while I can't see anything misplaced in the pictures, please doublecheck those that look similar, like the Liquid XP/Essence buckets, and maybe others, are in fact in the right place.  
And as Niller said, keep trying to click the output slot (even if empty) on every change, and even the table itself might not see it as "valid", but the server will.

**Comment by ylyxa** [comment]
> Usually, the issue is not actually the tanks, even if JEI likes to complain about them. Most of the time, JEI messes up the placement of the buckets, and while I can't see anything misplaced in the pictures, please doublecheck those that look similar, like the Liquid XP/Essence buckets, and maybe others, are in fact in the right place. And as Niller said, keep trying to click the output slot (even if empty) on every change, and even the table itself might not see it as "valid", but the server will.

OK I found the problem, wrong type of tree oil in one of the tanks.
